# -*- coding: utf-8 -*-
"""spotify_keys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NawavStYy-Fx7kt9ZSjAy9nvtjIhPaFT
"""

CLIENT_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CLIENT_SECRET = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# As chaves de acesso foram ocultadas p/ disponibilizar este arquivo online